# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-19 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='date_reimbursed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
